export const GRAPHPAPER_STORE_COPY = {
  brandLine: "WHITE TEE",
  nav: {
    all: "ALL",
    tops: "TOPS",
    topsAll: "All Tops",
    topsShortSleeve: "Short Sleeve",
    topsLongSleeve: "Long Sleeve",
    fabric: "FABRIC",
    fabricAll: "All Fabrics",
    journal: "JOURNAL",
    journalAll: "All Entries",
    bag: "Bag",
  },
  announcement: {
    message: "Free shipping on orders over ¥10,000.",
    linkHref: "/store-guide",
    linkLabel: "Store Guide",
  },
  plp: {
    title: "TOPS",
    allTitle: "ALL",
    items: (count: number) => `${count} ITEM${count === 1 ? "" : "S"}`,
  },
  filters: {
    title: "Filter",
    fabric: "Fabric",
    sleeve: "Sleeve",
    fit: "Fit",
    availability: "Availability",
    inStock: "In stock",
    all: "All",
  },
  cart: {
    title: "Your bag",
    empty: "Your bag is currently empty.",
    pairWith: "Pair with",
    orderNotes: "Add order notes",
    orderNotesPlaceholder: "Leave a note about your order",
    items: "Items",
    subtotal: "Subtotal",
    shipping: "Shipping",
    shippingFree: "Free",
    shippingFlat: "¥600",
    total: "Total",
    taxIncluded: "Tax included",
    checkout: "Check Out",
    viewAll: "View all pieces",
    exploreFabric: "Fabric",
    processing: "Processing…",
    remove: "Remove",
    unavailable: "Unavailable — remove to continue",
    checkoutFailed: "Checkout failed.",
    checkoutBlocked: "Remove unavailable items to continue",
    decreaseQty: "Decrease quantity",
    increaseQty: "Increase quantity",
    freeShippingProgress: (remaining: string) =>
      `${remaining} more for free shipping`,
    freeShippingReached: "Free shipping applied",
    shippingNote:
      "Ships in 3–7 business days. Returns within 7 days if unworn.",
    dutiesNote:
      "Prices include tax. Shipping calculated at checkout.",
    size: "Size",
    qty: "Qty",
    priceUpdated: (price: string) => `Price updated to ${price}`,
  },
  checkout: {
    cancelled: "Checkout cancelled",
    paymentIncomplete: "Payment was not completed.",
    cancelRecovery: "Your bag is saved. Continue when ready.",
    backToBag: "Back to bag",
    backToLastProduct: "Back to the piece you viewed",
    viewProducts: "View all pieces",
    exploreFabric: "Fabric",
    thankYou: "Thank you",
    orderConfirmed: "Order confirmed. Confirmation email sent.",
    orderId: (id: string) => `Order ${id}`,
    nextSteps: "We will prepare your order shortly.",
    orderSummaryLabel: "Your order",
    paymentPending: "Payment pending",
    paymentUnconfirmed: "Payment could not be confirmed. Your bag is unchanged.",
  },
  states: {
    notFound: {
      label: "404",
      message: "Page not found.",
      back: "Back to home",
    },
    error: {
      label: "Error",
      message: "Something went wrong. Try again shortly.",
      retry: "Try again",
      back: "Back to home",
    },
    loading: "Loading",
  },
  home: {
    sectionAll: "ALL",
    sleeveShort: "SHORT SLEEVE",
    sleeveLong: "LONG SLEEVE",
    sectionTops: "TOPS",
    sectionFabric: "FABRIC",
    sectionJournal: "JOURNAL",
    viewAllFabric: "View all fabrics",
    viewAllJournal: "View all entries",
    journalIntro: "From the atelier",
  },
  footer: {
    storeGuide: "Store Guide",
    shipping: "Shipping",
    stockist: "Stockist",
    contact: "Contact",
    about: "About",
    journal: "Journal",
    fabric: "Fabric",
    privacy: "Privacy",
    terms: "Terms",
    legal: "Legal Notice",
  },
  pdp: {
    recentlyViewed: "Recently Viewed",
    color: "Color",
    colorValue: "White",
    dutiesNote: "Prices include tax. Shipping calculated at checkout.",
    addToBag: "Add to Bag",
    sku: "SKU",
    aboutFabric: (name: string) => `About ${name} →`,
    storeGuideTitle: "Store Guide",
    material: "Material",
    model: "Model",
    description: "Description",
    care: "Care",
    sizeGuide: "Size guide",
  },
} as const;
