import { RETURNS_POLICY } from "@/lib/store-ui/returns-policy";

export const GRAPHPAPER_STORE_COPY = {
  brandLine: "WHITE TEE",
  nav: {
    all: "ALL",
    tops: "TOPS",
    topsAll: "All Tops",
    topsShortSleeve: "Short Sleeve",
    topsLongSleeve: "Long Sleeve",
    fabric: "FABRIC",
    fabricAll: "All Fabrics",
    journal: "JOURNAL",
    journalAll: "All Entries",
    bag: "Bag",
  },
  announcement: {
    message: "¥10,000以上のご注文で送料無料。",
    linkHref: "/store-guide",
    linkLabel: "ご利用ガイド",
  },
  plp: {
    title: "TOPS",
    allTitle: "ALL",
    items: (count: number) => `${count} 点`,
  },
  filters: {
    title: "絞り込み",
    fabric: "生地",
    sleeve: "袖丈",
    fit: "フィット",
    availability: "在庫",
    inStock: "在庫あり",
    all: "すべて",
  },
  cart: {
    title: "カート",
    empty: "カートに商品がありません。",
    pairWith: "合わせてどうぞ",
    orderNotes: "ご注文メモ",
    orderNotesPlaceholder: "配送に関するご要望など",
    items: "商品",
    subtotal: "小計",
    shipping: "送料",
    shippingFree: "無料",
    shippingFlat: "¥600",
    total: "合計",
    taxIncluded: "税込",
    checkout: "レジに進む",
    continueShopping: "買い物を続ける",
    viewAll: "すべての商品を見る",
    exploreFabric: "生地について",
    processing: "処理中…",
    remove: "削除",
    unavailable: "在庫なし — 削除してください",
    checkoutFailed: "決済に失敗しました。",
    checkoutBlocked: "在庫切れ商品を削除してください",
    decreaseQty: "数量を減らす",
    increaseQty: "数量を増やす",
    freeShippingProgress: (remaining: string) =>
      `あと${remaining}で送料無料`,
    freeShippingReached: "送料無料が適用されました",
    shippingNote: RETURNS_POLICY.shippingNote,
    dutiesNote: "表示価格は税込。送料はレジで計算されます。",
    size: "サイズ",
    qty: "数量",
    priceUpdated: (price: string) => `価格を ${price} に更新しました`,
  },
  checkout: {
    cancelled: "決済がキャンセルされました",
    paymentIncomplete: "決済が完了しませんでした。",
    cancelRecovery: "カートは保存されています。準備ができたらお続けください。",
    backToBag: "カートに戻る",
    backToLastProduct: "閲覧していた商品に戻る",
    viewProducts: "すべての商品を見る",
    exploreFabric: "生地について",
    thankYou: "ご注文ありがとうございます",
    orderConfirmed: "ご注文を確認しました。確認メールをお送りしました。",
    orderId: (id: string) => `注文番号 ${id}`,
    nextSteps: "まもなく商品の準備を開始します。",
    orderSummaryLabel: "ご注文内容",
    paymentPending: "決済確認中",
    paymentUnconfirmed: "決済を確認できませんでした。カートはそのままです。",
  },
  states: {
    notFound: {
      label: "404",
      message: "Page not found.",
      back: "Back to home",
    },
    error: {
      label: "Error",
      message: "Something went wrong. Try again shortly.",
      retry: "Try again",
      back: "Back to home",
    },
    loading: "Loading",
  },
  home: {
    sectionAll: "ALL",
    sleeveShort: "SHORT SLEEVE",
    sleeveLong: "LONG SLEEVE",
    sectionTops: "TOPS",
    sectionFabric: "FABRIC",
    sectionJournal: "JOURNAL",
    viewAllFabric: "View all fabrics",
    viewAllJournal: "View all entries",
    journalIntro: "From the atelier",
  },
  footer: {
    storeGuide: "ご利用ガイド",
    shipping: "配送・返品",
    stockist: "Stockist",
    contact: "お問い合わせ",
    about: "About",
    journal: "Journal",
    fabric: "Fabric",
    privacy: "プライバシー",
    terms: "利用規約",
    legal: "特定商取引法",
  },
  pdp: {
    recentlyViewed: "最近見た商品",
    color: "カラー",
    colorValue: "ホワイト",
    dutiesNote: "表示価格は税込。送料はレジで計算されます。",
    addToBag: "カートに入れる",
    sku: "SKU",
    aboutFabric: (name: string) => `${name} について →`,
    storeGuideTitle: "ご利用ガイド",
    material: "素材",
    model: "モデル",
    description: "商品説明",
    care: "お手入れ",
    sizeGuide: "サイズガイド",
  },
} as const;
