/** Shared UI copy — quiet, consistent brand voice. */
export const SITE_UI_COPY = {
  nav: {
    fabric: "Fabric",
    products: "Products",
  },
  cart: {
    title: "Bag",
    empty: "Bag is empty.",
    continue: "Continue",
    checkout: "Checkout",
    subtotal: "Subtotal",
    shipping: "Shipping",
    shippingFree: "Free",
    shippingFlat: "¥600",
    total: "Total",
    taxIncluded: "Tax included",
    processing: "Processing…",
    remove: "Remove",
    unavailable: "Unavailable — remove to continue",
    checkoutFailed: "Checkout failed.",
    checkoutBlocked: "Remove unavailable items to continue",
    decreaseQty: "Decrease quantity",
    increaseQty: "Increase quantity",
    freeShippingProgress: (remaining: string) =>
      `${remaining} more for free shipping`,
    freeShippingReached: "Free shipping applied",
    shippingNote: "Ships in 3–7 business days. Returns within 7 days if unworn.",
    exploreFabric: "Explore fabric",
    viewProducts: "View pieces",
  },
  product: {
    selectSize: "Select size",
    selectSizeButton: "Select Size",
    addToBag: "Add to Bag",
    outOfStock: "Out of Stock",
    maxInBag: "Max in Bag",
    chooseSize: "Select size to continue",
    unavailable: "Size unavailable",
    allInBag: "All units in bag",
    inBagMore: (inBag: number, more: number) => `${inBag} in bag · ${more} more`,
    added: (size: string, qty?: number) =>
      qty && qty > 1 ? `${size} · ${qty} added` : `${size} added`,
    viewBag: "View bag",
    size: "Size",
    sizeGuide: "Size guide",
    qty: "Qty",
    qtyLeft: (n: number) => `${n} left`,
    sizeSelected: (size: string) => `${size} selected`,
    priceUpdated: (price: string) => `Price updated to ${price}`,
    modelCaption: "Model",
    measurementsLabel: "Measurements (cm)",
    scrollHint: "Scroll →",
    plpIntro: "Every piece begins with the cloth.",
    plpIntroSub: "Choose by fabric, then by fit.",
    filteredIntro: (fabricName: string) => `Pieces in ${fabricName}.`,
  },
  modelFit: {
    sectionLabel: "Model and fit",
    modelLine: (heightCm: number, weightKg: number) =>
      `Model is ${heightCm}cm / ${weightKg}kg`,
    wearingSize: (size: string) => `Wearing size ${size}`,
    modelLineJa: (heightCm: number, weightKg: number, size: string) =>
      `モデル ${heightCm}cm・${weightKg}kg、着用サイズ ${size}`,
    moreModels: "Also worn by",
  },
  sizeRecommendation: {
    sectionLabel: "Size recommendation",
    heading: "Find your size",
    height: "Height (cm)",
    weight: "Weight (kg)",
    preference: "Fit preference",
    submit: "See recommendation",
    disclaimer: "A guide only — fit varies by body shape and styling.",
    invalidInput: "Enter height and weight within the ranges shown.",
  },
  fabric: {
    title: "Fabric",
    introLine: "Every white tee begins with the cloth.",
    introSubline: "Weight, hand, and how quietly it holds light.",
    allFabrics: "All fabrics",
    inThisFabric: "Same fabric",
    thisFabric: "This fabric",
    viewAll: "All pieces",
    exploreFabric: "Explore fabric",
    characterScale: "Each row is a quiet scale from light to full.",
    pieceCount: (count: number) =>
      count === 1 ? "1 piece" : `${count} pieces`,
    character: {
      thickness: "Thickness",
      softness: "Softness",
      structure: "Structure",
      sheerness: "Sheerness",
      surface: "Surface",
    },
  },
  home: {
    selection: "Selection",
    allPieces: "All pieces",
    exploreFabric: "Explore fabric",
  },
  checkout: {
    thankYou: "Thank you",
    orderConfirmed: "Order confirmed. Confirmation email sent.",
    orderId: (id: string) => `Order ${id}`,
    nextSteps: "We will prepare your order shortly.",
    paymentPending: "Payment pending",
    paymentUnconfirmed: "Payment could not be confirmed. Your bag is unchanged.",
    cancelled: "Checkout cancelled",
    paymentIncomplete: "Payment was not completed.",
    cancelRecovery: "Your bag is saved. Continue when ready.",
    backToBag: "Back to bag",
    continue: "Continue",
    exploreFabric: "Explore fabric",
    viewProducts: "View pieces",
  },
  breadcrumbs: {
    home: "Home",
    fabric: "Fabric",
    products: "Products",
  },
  states: {
    notFound: {
      label: "404",
      message: "Page not found.",
      back: "Back",
    },
    error: {
      label: "Error",
      message: "Something went wrong. Try again shortly.",
      retry: "Try again",
      back: "Back",
    },
    loading: "Loading",
  },
} as const;
