/** Shared UI copy — quiet, consistent brand voice. */
import { RETURNS_POLICY } from "@/lib/store-ui/returns-policy";

export const SITE_UI_COPY = {
  nav: {
    fabric: "Fabric",
    products: "Products",
  },
  cart: {
    title: "カート",
    empty: "カートに商品がありません。",
    continue: "買い物を続ける",
    checkout: "レジに進む",
    subtotal: "小計",
    shipping: "送料",
    shippingFree: "無料",
    shippingFlat: "¥600",
    total: "合計",
    taxIncluded: "税込",
    processing: "処理中…",
    remove: "削除",
    unavailable: "在庫なし — 削除してください",
    checkoutFailed: "決済に失敗しました。",
    checkoutBlocked: "在庫切れ商品を削除してください",
    decreaseQty: "数量を減らす",
    increaseQty: "数量を増やす",
    freeShippingProgress: (remaining: string) =>
      `あと${remaining}で送料無料`,
    freeShippingReached: "送料無料が適用されました",
    shippingNote: RETURNS_POLICY.shippingNote,
    exploreFabric: "生地について",
    viewProducts: "商品一覧",
  },
  product: {
    selectSize: "サイズを選択",
    selectSizeButton: "サイズを選ぶ",
    addToBag: "カートに入れる",
    outOfStock: "在庫切れ",
    maxInBag: "カート上限",
    chooseSize: "サイズを選んでください",
    unavailable: "在庫なし",
    allInBag: "在庫分すべてカートに入っています",
    inBagMore: (inBag: number, more: number) =>
      `カート ${inBag}点 · あと${more}点追加可`,
    added: (size: string, qty?: number) =>
      qty && qty > 1 ? `${size} · ${qty}点追加しました` : `${size} を追加しました`,
    viewBag: "カートを見る",
    size: "サイズ",
    sizeGuide: "サイズガイド",
    qty: "数量",
    qtyLeft: (n: number) => `残り${n}点`,
    sizeSelected: (size: string) => `${size} を選択中`,
    priceUpdated: (price: string) => `価格を ${price} に更新しました`,
    modelCaption: "モデル",
    measurementsLabel: "採寸（cm）",
    scrollHint: "スクロール →",
    plpIntro: "まず生地から。",
    plpIntroSub: "生地、そしてフィット。",
    filteredIntro: (fabricName: string) => `${fabricName}。`,
    reassurance: {
      shipping: RETURNS_POLICY.shipping,
      returns: RETURNS_POLICY.returns,
      shippingLink: RETURNS_POLICY.shippingLink,
      helperJa: RETURNS_POLICY.helperJa,
    },
    gallerySwipeHint: "スワイプ →",
    sizeTableHeaders: ["サイズ", "着丈", "肩幅", "身幅", "袖丈"] as const,
    sizeTableCaption: "サイズガイド（cm）",
    sizeTableExplainer:
      "後ろ首下から裾まで。肩端から肩端。身幅は平置き採寸。",
  },
  modelFit: {
    sectionLabel: "モデルとフィット",
    modelLine: (heightCm: number, weightKg: number) =>
      `モデル ${heightCm}cm / ${weightKg}kg`,
    wearingSize: (size: string) => `着用サイズ ${size}`,
    modelLineJa: (heightCm: number, weightKg: number, size: string) =>
      `モデル ${heightCm}cm・${weightKg}kg、着用サイズ ${size}`,
    moreModels: "他のモデル",
    sizeHint: "普段のTシャツと同じサイズからお試しください。",
  },
  sizeRecommendation: {
    sectionLabel: "サイズの目安",
    heading: "サイズを探す",
    height: "身長（cm）",
    weight: "体重（kg）",
    preference: "着用の好み",
    preferences: [
      { value: "just-fit" as const, label: "ジャスト" },
      { value: "relaxed" as const, label: "ゆったり" },
      { value: "oversized" as const, label: "オーバーサイズ" },
    ],
    submit: "おすすめを見る",
    disclaimer: "目安です — 体型や着方で異なります。",
    invalidInput: "表示範囲内の身長・体重を入力してください。",
  },
  fabric: {
    title: "生地",
    introLine: "まず生地から。",
    introSubline: "厚み、手触り、光の通り方。",
    allFabrics: "すべての生地",
    inThisFabric: "同じ生地",
    thisFabric: "この生地",
    viewAll: "すべての商品",
    exploreFabric: "生地について",
    pieceCount: (count: number) => `${count}点`,
    character: {
      thickness: "厚み",
      softness: "やわらかさ",
      structure: "ハリ",
      sheerness: "透け感",
      surface: "表面感",
    },
    compareTitle: "比較",
    viewFabric: "生地",
  },
  home: {
    selection: "Selection",
    allPieces: "すべての商品",
    exploreFabric: "生地について",
    heroFabricLine: "Knitted in Wakayama.",
  },
  checkout: {
    thankYou: "ご注文ありがとうございます",
    orderConfirmed: "ご注文を確認しました。確認メールをお送りしました。",
    orderId: (id: string) => `注文番号 ${id}`,
    nextSteps: "まもなく商品の準備を開始します。",
    orderSummaryLabel: "ご注文内容",
    paymentPending: "決済確認中",
    paymentUnconfirmed: "決済を確認できませんでした。カートはそのままです。",
    cancelled: "決済がキャンセルされました",
    paymentIncomplete: "決済が完了しませんでした。",
    cancelRecovery: "カートは保存されています。準備ができたらお続けください。",
    backToLastProduct: "閲覧していた商品に戻る",
    backToBag: "カートに戻る",
    continue: "買い物を続ける",
    exploreFabric: "生地について",
    viewProducts: "商品一覧",
  },
  breadcrumbs: {
    home: "Home",
    fabric: "Fabric",
    products: "Products",
  },
  states: {
    notFound: {
      label: "404",
      message: "ページが見つかりません。",
      back: "戻る",
    },
    error: {
      label: "Error",
      message: "問題が発生しました。しばらくしてからお試しください。",
      retry: "再試行",
      back: "戻る",
    },
    loading: "読み込み中",
  },
} as const;
