/** Shared UI copy — quiet, consistent brand voice. */
export const SITE_UI_COPY = {
  cart: {
    title: "Bag",
    empty: "Bag is empty.",
    continue: "Continue",
    checkout: "Checkout",
    total: "Total",
    processing: "Processing…",
    remove: "Remove",
    unavailable: "Unavailable — remove to continue",
    checkoutFailed: "Checkout failed.",
    decreaseQty: "Decrease quantity",
    increaseQty: "Increase quantity",
  },
  product: {
    selectSize: "Select size",
    selectSizeButton: "Select Size",
    addToBag: "Add to Bag",
    outOfStock: "Out of Stock",
    maxInBag: "Max in Bag",
    chooseSize: "Select size to continue",
    unavailable: "Size unavailable",
    allInBag: "All units in bag",
    inBagMore: (inBag: number, more: number) => `${inBag} in bag · ${more} more`,
    added: (size: string, qty?: number) =>
      qty && qty > 1 ? `${size} · ${qty} added` : `${size} added`,
    viewBag: "View bag",
    size: "Size",
    qty: "Qty",
    qtyLeft: (n: number) => `${n} left`,
    sizeSelected: (size: string) => `${size} selected`,
    priceUpdated: (price: string) => `Price updated to ${price}`,
  },
  fabric: {
    title: "Fabric",
    introLine: "Every white tee begins with the cloth.",
    introSubline: "Weight, hand, and how quietly it holds light.",
    allFabrics: "All fabrics",
    inThisFabric: "Same fabric",
    thisFabric: "This fabric",
    viewAll: "All pieces",
  },
  home: {
    selection: "Selection",
    allPieces: "All pieces",
  },
  checkout: {
    thankYou: "Thank you",
    orderConfirmed: "Order confirmed. Confirmation email sent.",
    paymentPending: "Payment pending",
    paymentUnconfirmed: "Payment could not be confirmed. Your bag is unchanged.",
    cancelled: "Checkout cancelled",
    paymentIncomplete: "Payment was not completed.",
    backToBag: "Back to bag",
    continue: "Continue",
  },
  states: {
    notFound: {
      label: "404",
      message: "Page not found.",
      back: "Back",
    },
    error: {
      label: "Error",
      message: "Something went wrong. Try again shortly.",
      retry: "Try again",
      back: "Back",
    },
    loading: "Loading",
  },
} as const;
