/** Japanese admin UI copy — internal tooling, not storefront voice. */

export const ADMIN_COPY = {
  nav: {
    dashboard: "ダッシュボード",
    orders: "注文",
    products: "商品",
    fabrics: "生地",
    content: "ホームページ設定",
    pages: "固定ページ",
    seo: "SEO設定",
    store: "ECサイト",
    logout: "ログアウト",
    loggingOut: "ログアウト中…",
  },
  common: {
    back: "← 戻る",
    backToDashboard: "← ダッシュボードへ",
    backToOrders: "← 注文一覧へ",
    backToProducts: "← 商品一覧へ",
    notFoundOrder: "注文が見つかりません。",
    notFoundProduct: "商品が見つかりません。",
    save: "保存",
    saving: "保存中…",
    create: "作成",
    delete: "削除",
    cancel: "キャンセル",
    edit: "編集",
    all: "すべて",
    count: (n: number, unit: string) => `${n}件の${unit}`,
    saved: "保存しました。",
    saveFailed: "保存に失敗しました。",
    signInFailed: "ログインに失敗しました。",
    unsavedChanges: "未保存の変更があります。タブを切り替えますか？",
    leaveUnsaved: "このページを離れますか？未保存の変更は失われます。",
  },
  confirm: {
    title: "確認",
    proceed: "続行",
  },
  pagination: {
    label: "ページネーション",
    prev: "前へ",
    next: "次へ",
    pageOf: (page: number, totalPages: number, total: number) =>
      `${total}件中 ${page} / ${totalPages} ページ`,
  },
  login: {
    title: "管理画面ログイン",
    password: "パスワード",
    submit: "ログイン",
    submitting: "ログイン中…",
  },
  dashboard: {
    title: "管理画面",
    subtitle: "注文・商品・コンテンツを管理します。",
    stats: {
      unshipped: "未発送（支払済）",
      unshippedHint: "ステータスが「支払済」の注文数",
      lowStock: "在庫わずか",
      lowStockEmpty: "在庫わずかの商品はありません。",
      stockRemaining: (n: number) => `合計在庫 ${n}`,
      recentOrders: "最近の注文",
      recentOrdersEmpty: "注文はまだありません。",
    },
  },
  sections: {
    orders: {
      label: "注文",
      description: "検索・フィルター・CSVエクスポート",
    },
    products: {
      label: "商品",
      description: "商品の追加・編集・在庫管理",
    },
    fabrics: {
      label: "生地",
      description: "生地の文言・画像編集",
    },
    content: {
      label: "ホームページ設定",
      description: "Home / About の文言編集（Journal はコード管理）",
    },
    pages: {
      label: "固定ページ",
      description: "Legal / Contact / Shipping / Privacy / Terms",
    },
    seo: {
      label: "SEO設定",
      description: "サイト名・説明文・OGP画像",
    },
  },
  orders: {
    title: "注文一覧",
    detailTitle: "注文詳細",
    search: "検索",
    searchPlaceholder: "注文ID または メールアドレス",
    status: "ステータス",
    exportCsv: "CSVをダウンロード",
    showing: (filtered: number, total: number) =>
      `${total}件中 ${filtered}件を表示`,
    totalAmount: (amount: string) => `合計 ${amount}`,
    empty: "注文はまだありません。",
    emptyFiltered: "条件に一致する注文がありません。",
    resendNotConfigured:
      "発送通知メールは未設定です（RESEND_API_KEY を .env に設定してください）。",
    columns: {
      id: "注文ID",
      email: "メール",
      date: "日付",
      total: "合計",
      status: "ステータス",
      payment: "決済",
    },
    items: "注文商品",
    itemsEmpty: "注文商品がありません。",
    itemColumns: {
      product: "商品",
      size: "サイズ",
      qty: "数量",
      unitPrice: "単価",
      subtotal: "小計",
    },
    updateStatus: "ステータスを更新",
    updating: "更新中…",
    statusUpdated: "ステータスを更新しました。",
    statusUpdateFailed: "ステータス更新に失敗しました。",
  },
  products: {
    title: "商品一覧",
    add: "商品を追加",
    new: "新規商品",
    edit: "商品を編集",
    empty: "商品はまだありません。",
    search: "検索",
    searchPlaceholder: "商品名またはスラッグ",
    filterStatus: "公開状態",
    showing: (filtered: number, total: number) =>
      `${total}件中 ${filtered}件を表示`,
    supabaseRequired:
      "Supabase が未設定です。環境変数と DATA_SOURCE=supabase を設定してください。",
    columns: {
      product: "商品",
      price: "価格",
      stock: "在庫",
      status: "公開",
      updated: "更新日",
    },
    published: "公開中",
    draft: "非公開",
    sections: {
      basic: "基本情報",
      material: "素材・お手入れ",
      images: "画像",
      variants: "サイズ・在庫",
      sizeGuide: "サイズ表（cm）",
      fitProfile: "モデル・フィット",
    },
    fields: {
      name: "商品名",
      slug: "スラッグ（URL）",
      price: "価格（円）",
      fabric: "生地",
      fabricPlaceholder: "生地を選択",
      published: "店舗に公開する",
      description: "短い説明（一覧・SEO）",
      detailDescription: "詳細説明（商品ページ）",
      fitNote: "フィットメモ",
      material: "素材",
      care: "お手入れ",
      addImageUrl: "画像URL",
      addImage: "追加",
      uploadImage: "画像をアップロード",
      primary: "メイン画像",
      cardHover: "一覧ホバー画像",
      cardHoverHint: "トップ・商品一覧でカーソルを合わせた時に表示",
      cardHoverNone: "ホバー画像なし",
      removeImage: "削除",
      imageRequired: "保存前に画像を1枚以上追加してください。",
      enableSize: "有効",
      size: "サイズ",
      sku: "SKU",
      stock: "在庫",
      length: "着丈",
      shoulder: "肩幅",
      chest: "身幅",
      sleeve: "袖丈",
      sleeveType: "袖丈（半袖 / 長袖）",
      enableOneSize: "サイズを1つ以上有効にしてください。",
      fitType: "フィットタイプ",
      fitLabel: "フィットラベル（店舗表示）",
      fitTypeSizeOffset: "フィットタイプ補正",
      fitTypeSizeOffsetHint: "サイズ推奨の基準サイズをずらす（例: boxy +1、slim -1）",
      models: "モデル情報",
      modelHeight: "身長（cm）",
      modelWeight: "体重（kg）",
      modelSize: "着用サイズ",
      modelLabel: "ラベル（任意）",
      modelLabelPlaceholder: "例: Model A",
      addModel: "モデルを追加",
      removeModel: "削除",
      sizeReference: "サイズ目安（身長帯）",
      heightMin: "身長 min",
      heightMax: "身長 max",
      heightLabel: "表示ラベル",
      preferenceAdjustments: "フィット好みの補正",
      preferenceAdjustmentsHint:
        "サイズ推奨ツールで、好みに応じてサイズをずらす量（整数）",
      preferenceOffset: (key: "justFit" | "relaxed" | "oversized") =>
        ({
          justFit: "ジャストフィット",
          relaxed: "ゆったり",
          oversized: "オーバーサイズ",
        })[key],
    },
    create: "商品を作成",
    saveChanges: "変更を保存",
    createFailed: "商品の作成に失敗しました。",
    saveFailed: "商品の保存に失敗しました。",
    deleteTitle: "商品を削除",
    deleteConfirm: (name: string) =>
      `「${name}」を削除します。元に戻せません。`,
    unpublishConfirm: (name: string) =>
      `「${name}」は注文履歴があるため、削除の代わりに非公開にします。続行しますか？`,
    unpublish: "非公開にする",
    processing: "処理中…",
    deleteFailed: "削除に失敗しました。",
    deleted: "削除しました。",
  },
  fabrics: {
    title: "生地一覧",
    edit: "生地を編集",
    empty: "生地はまだありません。",
    backToList: "← 生地一覧へ",
    saveChanges: "変更を保存",
    saveFailed: "生地の保存に失敗しました。",
    columns: {
      name: "名前",
      tagline: "タグライン",
      sortOrder: "表示順",
    },
    fields: {
      slug: "スラッグ",
      name: "名前",
      tagline: "タグライン",
      descriptionLines: "説明（1行ずつ改行）",
      image: "画像",
      imageAlt: "画像 alt",
      sortOrder: "表示順",
      character: "Fabric Character（1〜5）",
      characterThickness: "Thickness",
      characterSoftness: "Softness",
      characterStructure: "Structure",
      characterSheerness: "Sheerness",
      characterSurface: "Surface",
    },
  },
  content: {
    title: "ホームページ設定",
    subtitle:
      "店舗に表示される Home / About の文言を編集します。Journal は lib/content/journal.ts を参照。",
    tabs: {
      home: "Home",
      about: "About",
      stories: "Stories（旧）",
    },
    journalNotice:
      "ストアフロントの Journal（/journal）はコード側の lib/content/journal.ts で管理されています。このタブは旧 Stories CMS 用です。",
    imageField: {
      pathOrUrl: "画像パス / URL",
      upload: "画像をアップロード",
      uploading: "アップロード中…",
      uploadFailed: "画像のアップロードに失敗しました。",
    },
    home: {
      heroImage: "Hero 画像",
      heroImageHint:
        "横長 16:9 推奨（例 1920×1080）。被写体は中央〜やや上に。最大 5 MB（JPEG / PNG / WebP / GIF）。",
      heroCopy: "Hero コピー",
      concept1: "コンセプト 1行目",
      concept2: "コンセプト 2行目",
      featuredCount: "おすすめ商品の表示件数",
      fabricPreviewCount: "生地プレビュー表示件数",
      fabricIntro1: "生地イントロ 1行目",
      fabricIntro2: "生地イントロ 2行目",
      featuredSlugs: "おすすめ商品（手動指定）",
      featuredSlugsHint: "未選択の場合は自動アルゴリズムで選定されます。",
      featuredSlugsEmpty: "公開中の商品がありません。",
    },
    about: {
      headline: "見出し",
      paragraph: (n: number) => `段落 ${n}（1行ずつ改行）`,
    },
    stories: {
      pageTitle: "ページタイトル",
      intro1: "イントロ 1行目",
      intro2: "イントロ 2行目",
      entry: (n: number) => `ストーリー ${n}`,
      title: "タイトル",
      lines: "本文（1行ずつ改行）",
      imagePath: "画像",
      imagePathHint:
        "4:3 推奨（例 1600×1200）。最大 5 MB（JPEG / PNG / WebP / GIF）。",
      imageAlt: "画像 alt",
    },
    saveTab: (tab: string) => `${tab} を保存`,
  },
  pages: {
    title: "固定ページ",
    subtitle: "Legal / Contact / Shipping / Privacy / Terms の文言を編集します。",
    tabs: {
      legal: "店舗情報",
      contact: "Contact",
      shipping: "Shipping",
      privacy: "Privacy",
      terms: "Terms",
    },
    legal: {
      operator: "販売業者",
      address: "所在地",
      email: "メール",
      phone: "電話番号",
    },
    contact: {
      intro1: "イントロ 1行目",
      intro2: "イントロ 2行目",
      email: "メールアドレス",
      hours: "受付時間",
    },
    policy: {
      pageTitle: "ページタイトル",
      section: (n: number) => `セクション ${n}`,
      sectionTitle: "見出し",
      sectionBody: "本文",
    },
    saveTab: (tab: string) => `${tab} を保存`,
  },
  seo: {
    title: "SEO設定",
    subtitle: "サイト全体の SEO 設定を編集します。",
    siteName: "サイト名",
    siteDescription: "サイト説明",
    defaultOgpImage: "デフォルト OGP 画像",
    defaultOgpImageHint: "パス（例 /home/hero.svg）または URL",
    twitterHandle: "Twitter @handle（任意）",
    save: "SEO設定を保存",
  },
  status: {
    pending: "処理待ち",
    paid: "支払済",
    shipped: "発送済",
    cancelled: "キャンセル",
    failed: "失敗",
  },
  payment: {
    paid: "支払済",
    unpaid: "未払い",
    pending: "処理中",
    failed: "失敗",
  },
  orderDetail: {
    summaryTitle: "注文情報",
    id: "注文ID",
    email: "メール",
    emailNotRegistered: "未登録",
    date: "注文日時",
    total: "合計",
    status: "ステータス",
    payment: "決済状態",
    shipping: "配送先",
    shippingNotRegistered: "未登録",
    orderNotes: "注文メモ",
    orderNotesEmpty: "なし",
    stripePayment: "Stripe 決済",
  },
} as const;
